site_name: CompTIA A+ Bible

theme:
  name: material

nav:
  - About: index.md
  - Core 1:
      - 1 Mobile Devices:
          - 1.1 Algorithms: Chap01/1.1.md
          - 1.2 Algorithms as a technology: Chap01/1.2.md
          - Chap 1 Problems:
              - Problem 1-1: Chap01/Problems/1-1.md
      - 2 Getting Started:
          - 2.1 Insertion sort: Chap02/2.1.md
          - 2.2 Analyzing algorithms: Chap02/2.2.md
          - 2.3 Designing algorithms: Chap02/2.3.md
          - Chap 2 Problems:
              - 2-1 Insertion sort on small arrays in merge sort: Chap02/Problems/2-1.md
              - 2-2 Correctness of bubblesort: Chap02/Problems/2-2.md
              - 2-3 Correctness of Horner's rule: Chap02/Problems/2-3.md
              - 2-4 Inversions: Chap02/Problems/2-4.md
  - Core 2:
      - 1 The Role of Algorithms in Computing:
          - 1.1 Algorithms: Chap01/1.1.md
          - 1.2 Algorithms as a technology: Chap01/1.2.md
          - Chap 1 Problems:
              - Problem 1-1: Chap01/Problems/1-1.md
      - 2 Getting Started:
          - 2.1 Insertion sort: Chap02/2.1.md
          - 2.2 Analyzing algorithms: Chap02/2.2.md
          - 2.3 Designing algorithms: Chap02/2.3.md
          - Chap 2 Problems:
              - 2-1 Insertion sort on small arrays in merge sort: Chap02/Problems/2-1.md
              - 2-2 Correctness of bubblesort: Chap02/Problems/2-2.md
              - 2-3 Correctness of Horner's rule: Chap02/Problems/2-3.md
              - 2-4 Inversions: Chap02/Problems/2-4.md
  - Core 1 Practice Exams:
      - 1 Practice Exam A:
          - 1.1 Algorithms: Chap01/1.1.md
          - 1.2 Algorithms as a technology: Chap01/1.2.md
          - Chap 1 Problems:
              - Problem 1-1: Chap01/Problems/1-1.md
      - 2 Getting Started:
          - 2.1 Insertion sort: Chap02/2.1.md
          - 2.2 Analyzing algorithms: Chap02/2.2.md
          - 2.3 Designing algorithms: Chap02/2.3.md
          - Chap 2 Problems:
              - 2-1 Insertion sort on small arrays in merge sort: Chap02/Problems/2-1.md
              - 2-2 Correctness of bubblesort: Chap02/Problems/2-2.md
              - 2-3 Correctness of Horner's rule: Chap02/Problems/2-3.md
              - 2-4 Inversions: Chap02/Problems/2-4.md
